FROM  amazonlinux:2023

RUN dnf -y install glibc-langpack-ja
RUN dnf -y install java-17-amazon-corretto-devel
COPY conf/log4j2.xml /log4j2.xml
COPY lib/kanjikana_api-WEB-jar-with-dependencies.jar /app.jar
COPY lib/kanjikana_core-WEB-jar-with-dependencies.jar /core.jar
COPY .djl.ai/ /root/.djl.ai/
COPY .cache/ /root/.cache/
ENTRYPOINT ["java","-Xmx8192M","-Dlog4j.configurationFile=/log4j2.xml","-cp","/core.jar","-jar","/app.jar" ]
